env:
  browser: true
  es2021: true
  node: true
plugins:
  - prettier
extends:
  - prettier
  - "plugin:prettier/recommended"
parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {
  "prettier/prettier": error
}
